---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# promote-draft-release-action
name: "⏫ Promote Draft Release"
description: "Promotes a draft GitHub release"

# When no inputs specified, defaults to the most recent/latest draft
inputs:
  # Optional
  TAG:
    description: 'Tag of draft release to promote'
    required: false
    type: 'string'
  NAME:
    description: 'Name of draft release to promote'
    required: false
    type: 'string'
  GITHUB_TOKEN:
    description: 'GitHub Token with write content permissions'
    required: true
    type: 'string'

runs:
  using: "composite"
  steps:
    - name: "Capture draft releases in repository"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        # Capture draft releases in repository

        # Note: GitHub token must have permissions: "content: write
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "Error: GitHub token not passed to action ❌"; exit 1
        else
          echo "Token: $GITHUB_TOKEN"
        fi

        # Use of GitHub CLI requires a valid token
        gh release list --json name,tagName,createdAt,isDraft
        gh release list
        echo "# Promote Draft Release ⏫" >> "$GITHUB_STEP_SUMMARY"
